"""System-prompt and style-pack loading.

The engine knows about no narrative universe: it exposes a set of generic
transforms (LTX rewrite, storyboard, translation, audio amplification...)
whose system prompts are plain text files, and it accepts external *packs*
that add their own routes or override the engine's.

A pack is a directory holding a ``pack.json``:

.. code-block:: json

    {
      "id": "example",
      "name": "Example",
      "transforms": {
        "/noir": {"tag": "NOIR", "system": "prompts/noir.txt"}
      },
      "overrides": {"chat": "prompts/chat.txt"}
    }

Packs live in ``PHOS_PACKS_DIR`` (default: ``packs/`` at the repository root).
No private pack is versioned; only ``packs/example`` is.
"""

from __future__ import annotations

import json
import logging
import os
import re
from dataclasses import dataclass, field
from pathlib import Path


logger = logging.getLogger(__name__)

#: Directory of the system prompts shipped with the engine.
BUILTIN_PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"

#: Style-pack root, overridable through the environment.
PACKS_DIR = Path(
    os.environ.get("PHOS_PACKS_DIR", Path(__file__).resolve().parents[2] / "packs")
)

#: Active pack at import time ("" = none, bare engine). Read again in load():
#: config.py imports this module 69 lines before it loads the .env, so a pack
#: named only in .env was invisible here and every documented first run got the
#: bare engine. Import order must not decide what the pack is.
ACTIVE_PACK = os.environ.get("PHOS_PACK", "").strip()


def _env_pack() -> str:
    """The active pack id, read from the environment at call time."""
    return os.environ.get("PHOS_PACK", ACTIVE_PACK).strip()


def _env_packs_dir() -> Path:
    """The pack root, read from the environment at call time."""
    override = os.environ.get("PHOS_PACKS_DIR", "").strip()
    return Path(override) if override else PACKS_DIR

#: Engine routes: prompt name -> (HTTP route, log tag, UI label).
BUILTIN_TRANSFORMS: dict[str, tuple[str, str, str]] = {
    "imgprompt": ("/imgprompt", "IMGPROMPT", "Image prompt"),
    "ltx": ("/ltx", "LTX", "LTX format"),
    "director": ("/director", "DIRECTOR", "Director framing"),
    "dialogue": ("/dialogue", "DIALOGUE", "Dialogue / voice-over"),
    "translate": ("/translate", "TRANSLATE", "Translate"),
    "ground": ("/ground", "GROUND", "Ground"),
    "amplify": ("/amplify", "AMPLIFY", "Amplify"),
}

#: Prompts used outside the routing table (called directly by the proxy).
STANDALONE_PROMPTS = ("ltx_i2v", "chat", "storyboard", "caption_video")

DEFAULT_MAX_TOKENS = 900
DEFAULT_TEMPERATURE = 0.65


@dataclass
class Cipher:
    """Character and phrase substitution applied after generation.

    Parameters
    ----------
    chars : dict of str to str
        Character-by-character transliteration table.
    phrases : dict of str to str
        Whole phrases replaced before transliteration, case-insensitively.
        They are protected by a marker for the duration of the character pass,
        otherwise their glyphs would be transliterated in turn.
    """

    chars: dict[str, str] = field(default_factory=dict)
    phrases: dict[str, str] = field(default_factory=dict)

    @classmethod
    def from_file(cls, path: Path) -> "Cipher":
        """Load a cipher from a ``{"chars": {}, "phrases": {}}`` JSON file."""
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls(chars=data.get("chars", {}), phrases=data.get("phrases", {}))

    def apply(self, text: str) -> str:
        """Apply the cipher to ``text``.

        Parameters
        ----------
        text : str
            Text generated by the LLM.

        Returns
        -------
        str
            Transliterated text, key phrases replaced by their glyph.
        """
        placeholders: dict[str, str] = {}
        for idx, (phrase, glyph) in enumerate(self.phrases.items()):
            marker = f"\x00{idx}\x00"
            pattern = re.compile(re.escape(phrase), re.IGNORECASE)
            if pattern.search(text):
                text = pattern.sub(marker, text)
                placeholders[marker] = glyph
        text = "".join(self.chars.get(ch, ch) for ch in text)
        for marker, glyph in placeholders.items():
            text = text.replace(marker, glyph)
        return text


@dataclass
class Transform:
    """A rewrite route served by the proxy.

    Parameters
    ----------
    route : str
        HTTP path (e.g. ``"/ltx"``).
    tag : str
        Short label used in the logs.
    system : str
        System prompt sent to the local LLM.
    max_tokens, temperature : int, float
        Generation settings specific to this transform.
    cipher : Cipher or None
        Optional post-processing applied to the output.
    """

    route: str
    tag: str
    system: str
    max_tokens: int = DEFAULT_MAX_TOKENS
    temperature: float = DEFAULT_TEMPERATURE
    cipher: Cipher | None = None
    label: str = ""
    pending: str = ""
    done: str = ""
    builtin: bool = False

    def postprocess(self, text: str) -> str:
        """Apply the pack's cipher if there is one, otherwise return as-is."""
        return self.cipher.apply(text) if self.cipher else text


class PromptLibrary:
    """Engine prompts, optionally extended or overridden by a pack."""

    def __init__(self, pack_id: str = "", packs_dir: Path | None = None) -> None:
        self.pack_id = pack_id
        self.packs_dir = packs_dir or PACKS_DIR
        self.pack_name = ""
        #: Character roster injected into the prompts that accept it.
        self.roster = ""
        #: Procedural corpus (word banks + presets) supplied by the pack.
        self.corpus: dict = {}
        #: Trained characters and LoRA trigger, supplied by the pack.
        self.characters: dict = {}
        self._prompts: dict[str, str] = {}
        self.transforms: dict[str, Transform] = {}
        self._load_builtins()
        if pack_id:
            self._load_pack(pack_id)

    # -- loading ------------------------------------------------------------
    def _load_builtins(self) -> None:
        for name in (*BUILTIN_TRANSFORMS, *STANDALONE_PROMPTS):
            path = BUILTIN_PROMPTS_DIR / f"{name}.txt"
            if not path.is_file():
                logger.warning("missing engine prompt: %s", path)
                continue
            self._prompts[name] = path.read_text(encoding="utf-8").strip()
        for name, (route, tag, label) in BUILTIN_TRANSFORMS.items():
            if name in self._prompts:
                self.transforms[route] = Transform(
                    route, tag, self._prompts[name], label=label, builtin=True
                )
        logger.info("engine: %d prompts, %d routes", len(self._prompts), len(self.transforms))

    def _load_pack(self, pack_id: str) -> None:
        root = self.packs_dir / pack_id
        manifest = root / "pack.json"
        if not manifest.is_file():
            logger.warning("pack '%s' not found in %s — bare engine", pack_id, self.packs_dir)
            return
        spec = json.loads(manifest.read_text(encoding="utf-8"))
        self.pack_name = spec.get("name", pack_id)

        if spec.get("characters"):
            chars_path = root / spec["characters"]
            if chars_path.is_file():
                self.characters = json.loads(chars_path.read_text(encoding="utf-8"))
            else:
                logger.warning("characters not found: %s", chars_path)


        if spec.get("corpus"):
            corpus_path = root / spec["corpus"]
            if corpus_path.is_file():
                self.corpus = json.loads(corpus_path.read_text(encoding="utf-8"))
            else:
                logger.warning("corpus not found: %s", corpus_path)

        if spec.get("roster"):
            roster_path = root / spec["roster"]
            if roster_path.is_file():
                self.roster = roster_path.read_text(encoding="utf-8").rstrip("\n")
            else:
                logger.warning("roster not found: %s", roster_path)

        for name, rel in (spec.get("overrides") or {}).items():
            path = root / rel
            if not path.is_file():
                logger.warning("override '%s' not found: %s", name, path)
                continue
            self._prompts[name] = path.read_text(encoding="utf-8").strip()
            if name in BUILTIN_TRANSFORMS:
                route, tag, label = BUILTIN_TRANSFORMS[name]
                self.transforms[route] = Transform(
                    route, tag, self._prompts[name], label=label, builtin=True
                )

        for route, cfg in (spec.get("transforms") or {}).items():
            path = root / cfg["system"]
            if not path.is_file():
                logger.warning("pack prompt not found: %s", path)
                continue
            cipher = None
            if cfg.get("cipher"):
                cipher_path = root / cfg["cipher"]
                if cipher_path.is_file():
                    cipher = Cipher.from_file(cipher_path)
                else:
                    logger.warning("cipher not found: %s", cipher_path)
            self.transforms[route] = Transform(
                route=route,
                tag=cfg.get("tag", route.strip("/").upper()),
                system=path.read_text(encoding="utf-8").strip(),
                max_tokens=int(cfg.get("max_tokens", DEFAULT_MAX_TOKENS)),
                temperature=float(cfg.get("temperature", DEFAULT_TEMPERATURE)),
                cipher=cipher,
                label=cfg.get("label", route.strip("/").capitalize()),
                pending=cfg.get("pending", ""),
                done=cfg.get("done", ""),
            )
        logger.info(
            "pack '%s' loaded: %d routes in total", self.pack_name, len(self.transforms)
        )

    # -- access -------------------------------------------------------------
    def prompt(self, name: str) -> str:
        """Return a system prompt by name, empty string if absent.

        ``{roster}`` is filled with the active pack's roster (empty with no
        pack) and ``{lang}`` with the configured spoken language, so an engine
        prompt stays valid with no pack loaded and no language baked in.
        """
        text = self._prompts.get(name, "")
        if "{roster}" in text:
            text = text.replace("{roster}", self.roster)
        if "{lang}" in text:
            # Imported here, not at module scope: the package __init__ pulls
            # personas in, so a top-level config import closes a cycle.
            from dynamic_video_generator import config
            text = text.replace("{lang}", config.DIALOGUE_LANG)
        return text

    def transform(self, route: str) -> Transform | None:
        """Return the transform served on ``route``, or ``None``."""
        return self.transforms.get(route)

    def routes(self) -> list[str]:
        """Sorted list of the active rewrite routes."""
        return sorted(self.transforms)

    def describe(self) -> dict:
        """Describe the active routes so the UI can build its buttons.

        Returns
        -------
        dict
            ``{"pack": str, "transforms": [{"route", "tag", "label",
            "pending", "done", "builtin"}, ...]}``. Non-``builtin`` entries
            come from the active pack: the UI renders those dynamically and
            shows nothing when no pack is loaded.
        """
        return {
            "pack": self.pack_name,
            "pack_id": self.pack_id,
            "transforms": [
                {
                    "route": tr.route,
                    "tag": tr.tag,
                    "label": tr.label or tr.tag.capitalize(),
                    "pending": tr.pending,
                    "done": tr.done,
                    "builtin": tr.builtin,
                }
                for tr in sorted(self.transforms.values(), key=lambda x: x.route)
            ],
        }


def load(pack_id: str | None = None, packs_dir: Path | None = None) -> PromptLibrary:
    """Build the prompt library for the requested pack.

    Parameters
    ----------
    pack_id : str, optional
        Pack identifier. Defaults to ``$PHOS_PACK`` (empty = bare engine).
    packs_dir : Path, optional
        Pack root. Defaults to ``$PHOS_PACKS_DIR``.

    Returns
    -------
    PromptLibrary
        A library ready to serve.
    """
    return PromptLibrary(
        pack_id if pack_id is not None else _env_pack(),
        packs_dir or _env_packs_dir(),
    )
